# ../../modules/desktop/niri.nix
{ config, pkgs, lib, ... }:

let
  user = config.myDesktop.primaryUser;

  # The greeter reads this fixed path at every login. Its *contents* are
  # regenerated by the Noctalia wallpaper-change hook
  # (home/niri.nix -> ~/.config/noctalia/hooks/greeter-blur.sh), so a new
  # wallpaper shows on the next login with no rebuild.
  greeterWallpaperDir = "/var/lib/greeter-wallpaper";
  greeterWallpaper = "${greeterWallpaperDir}/login.png";

  # First-login fallback, blurred+tinted with neutral defaults so the
  # greeter has something before the hook first runs.
  greeterSeed = pkgs.runCommand "greeter-wallpaper-seed.png"
    { nativeBuildInputs = [ pkgs.imagemagick ]; } ''
      magick ${../../wallpapers/login.png} \
        -auto-orient -resize '2560x1440^' -gravity center -extent 2560x1440 \
        -blur 0x10 -fill '#000000' -colorize 30% \
        png:$out
    '';
in
lib.mkIf (config.myDesktop.stack == "niri") {
  ############################################################
  # Niri compositor (system-level enablement)
  ############################################################

  programs.niri = {
    enable = true;
  };

  # GTK/GSettings backend for app config (GNOME module sets this too).
  programs.dconf.enable = true;

  ############################################################
  # Display / login manager
  ############################################################

  programs.noctalia-greeter = {
    enable = true;
    settings = {
      appearance.scheme = "Synced";
      appearance.hide_logo = true;
      # Pinned mutable path; the hook rewrites the file, not this setting.
      appearance.wallpaper.path = greeterWallpaper;
      appearance.wallpaper.fill_mode = "crop";
    };
  };

  # Writable handoff dir: hook writes it as ${user}, greeter reads it.
  systemd.tmpfiles.rules = [
    "d ${greeterWallpaperDir} 0755 ${user} users - -"
    "C ${greeterWallpaper} 0644 ${user} users - ${greeterSeed}"
  ];

  ############################################################
  # Authentication / permissions
  ############################################################

  # Required for screen locking, polkit auth prompts, etc.
  security.polkit = {
    enable = true;
    enablePkexecWrapper = true;
  };

  # Secret service (used by e.g. Chromium, VSCode)
  services.gnome.gnome-keyring.enable = true;

  services.gnome.gcr-ssh-agent.enable = false;

  ############################################################
  # XDG portals (IMPORTANT: only define defaults here ONCE)
  ############################################################

  # Needed for portals (screen share, file pickers)
  xdg.portal = {
    enable = true;

    extraPortals = with pkgs; [
      xdg-desktop-portal-gtk
    ];

    # IMPORTANT:
    # Use mkDefault so KDE/GNOME modules can override cleanly if needed
    config.common.default = lib.mkDefault "gtk";
  };

  ############################################################
  # System packages required for Niri sessions
  ############################################################

  #  via xwayland-satellite (niri integrates it automatically)
  environment.systemPackages = with pkgs; [
    xwayland-satellite       # Xwayland outside your Wayland compositor
    polkit_gnome
    bibata-cursors
  ];

  environment.pathsToLink = [
    "share/thumbnailers"
  ];

  environment.sessionVariables = {
    XDG_SESSION_DESKTOP = "niri";

    # Wayland session, not GPU-specific: applies to every host.
    NIXOS_OZONE_WL = "1";      # Chromium / Electron
    MOZ_ENABLE_WAYLAND = "1";  # Firefox
  };
}
