# ../../modules/apps/default.nix
{
  imports = [
#    ./android.nix
    ./ardour.nix
    ./audacity.nix
    ./bambu-studio.nix
    ./blender.nix
    ./bottles.nix
    ./chiaki-ng.nix
    ./darktable.nix
    ./firefox.nix
    ./freecad.nix
    ./freetube.nix
    ./gimp.nix
    ./godot.nix
    ./handbrake.nix
    ./iptvnator.nix
    ./kate.nix
    ./krita.nix
    ./losslesscut.nix
    ./lutris.nix
    ./mkvtoolnix.nix
    ./moonlight.nix
    ./mpv.nix
    ./obs-studio.nix
    ./office.nix
    ./openscad.nix
    ./orca-slicer.nix
    ./plex.nix
    ./proton-pass.nix
    ./spotify.nix
    ./telegram.nix
    ./thunderbird.nix
    ./vlc.nix
    ./vscodium.nix
    ./zen-browser.nix
  ];
}
