[theme.templates]
enable_builtin_templates = true

builtin_ids = [
    "btop",
    "cava",
    "ghostty",
    "helix",
    "gtk3",
    "gtk4",
    "kcolorscheme",
    "niri",
    "qt",
]

enable_community_templates = true

community_ids = [
    "bat",
    "blender",
    "brave",
    "darktable",
    "discord",
    "fastfetch",
    "fzf",
    "gimp",
    "steam",
    "telegram",
    "vscode",
    "yazi",
    "zed",
    "zen-browser",
]

[theme.templates.user.oh_my_posh]
input_path = "templates/oh-my-posh.json"
output_path = "$XDG_CONFIG_HOME/oh-my-posh/quick-term.json"
